version: '3.4'

services:
  creditproposal.worker:
    image: creditproposalworker:dev
    container_name: "CreditProposal.Worker"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CreditProposal.Worker"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - E:\ProcessoSeletivo\workers-rabbitMQ\src\Services\CreditProposal.Worker:/app:rw
      - E:\ProcessoSeletivo\workers-rabbitMQ:/src:rw
      - C:\Users\Usuário\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Usuário\.nuget\packages:/.nuget/packages:ro
      - C:\Users\Usuário\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\Usuário\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/CreditProposal.Worker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
  customer.worker:
    image: customerworker:dev
    container_name: "Customer.Worker"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Customer.Worker"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - E:\ProcessoSeletivo\workers-rabbitMQ\src\Services\Customer.Worker:/app:rw
      - E:\ProcessoSeletivo\workers-rabbitMQ:/src:rw
      - C:\Users\Usuário\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Usuário\.nuget\packages:/.nuget/packages:ro
      - C:\Users\Usuário\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\Usuário\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/Customer.Worker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true

  requestcredicard.worker:
    image: requestcredicardworker:dev
    container_name: "RequestCrediCard.Worker"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RequestCrediCard.Worker"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - E:\ProcessoSeletivo\workers-rabbitMQ\src\Services\RequestCrediCard.Worker:/app:rw
      - E:\ProcessoSeletivo\workers-rabbitMQ:/src:rw
      - C:\Users\Usuário\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Usuário\.nuget\packages:/.nuget/packages:ro
      - C:\Users\Usuário\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\Usuário\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/RequestCrediCard.Worker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
